[package]
name = "rs2ts"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0.26"
syn = { version = "1.0.103", features = ["full", "extra-traits"] }
